{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5236995904d40663f2b819c85d93fccf17c4d14916f181c5d827fe0a7b69fa03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - deprecated >=1.2.6
    - opentelemetry-api ~=1.3
    - python >=3.5

test:
  imports:
    - opentelemetry.propagators.b3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  description: This library provides a propagator for the B3 format

extra:
  recipe-maintainers:
    - twoodwark
