{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_propagator_b3-{{ version }}.tar.gz
  sha256: 69134e6fe9147fe6fe869d203bd5f6dd7f4f6de835d9e9fbe4fe4754c38d32d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - deprecated >=1.2.6
    - opentelemetry-api >=1.3,<2.dev0

test:
  imports:
    - opentelemetry.propagators.b3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  description: This library provides a propagator for the B3 format

extra:
  recipe-maintainers:
    - twoodwark
