{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_propagator_b3-{{ version }}.tar.gz
  sha256: aa05f951099f7b402139de64aa9169dc692e02741ee95ad70a1454a6d4c76c81

build:
  script:  {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  skip: True  # [py<310]
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - deprecated >=1.2.6
    - opentelemetry-api ~=1.3

test:
  imports:
    - opentelemetry
    - opentelemetry.propagators.b3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    This library provides a propagator for the B3 format
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/master/propagator/opentelemetry-propagator-b3
  doc_url: https://github.com/open-telemetry/opentelemetry-python/blob/main/propagator/opentelemetry-propagator-b3/README.rst

extra:
  recipe-maintainers:
    - twoodwark
