{% set name = "opentelemetry-propagator-b3" %}
{% set version = "1.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 16f42fa7a30a41dd710c67832e63985def8f6eddd8425becb832ba20b40595b5

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  skip: true  # [py<39]
  number: 0
  entry_points:
    - b3 = opentelemetry.propagators.b3:B3SingleFormat
    - b3multi = opentelemetry.propagators.b3:B3MultiFormat

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.3,<2
    - typing_extensions >=4.5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.propagators.b3
  source_files:
    - tests/
  commands:
    - pip check
    - python -c "from opentelemetry.propagators.b3 import B3SingleFormat; B3SingleFormat()"
    - python -c "from opentelemetry.propagators.b3 import B3MultiFormat; B3MultiFormat()"
    - python -c "import pkg_resources; assert any(ep.name == 'b3' for ep in pkg_resources.iter_entry_points('opentelemetry_propagator'))"
    - python -c "import pkg_resources; assert any(ep.name == 'b3multi' for ep in pkg_resources.iter_entry_points('opentelemetry_propagator'))"
    - pytest -v tests
  requires:
    - pip
    - opentelemetry-sdk
    - pytest =7.4.4

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/propagator/opentelemetry-propagator-b3
  summary: OpenTelemetry B3 Propagator
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    This library provides a propagator for the B3 format
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/propagator/opentelemetry-propagator-b3
  doc_url: https://github.com/open-telemetry/opentelemetry-python/blob/main/propagator/opentelemetry-propagator-b3/README.rst

extra:
  recipe-maintainers:
    - twoodwark
